services:

# App service definition. It runs the latest image pushed to Amazon ECR.
  app:
    image: ${ECR_REPO}:latest
    container_name: cumulative-task
    restart: unless-stopped

    # Ports mapping is defined to expose the container's port 80 to the host machine's port 8080. 
    ## This allows access to the application running inside the container from the host machine.
    ports:
      - "8080:80"
